spring:
  application:
    name: library

  datasource:
    url: jdbc:mysql://localhost:3306/db_jae
    username: jae
    password: Jae2525!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
